---
- name: Install Nvidia Device Plugin to work with Kubernetes Control Node
  hosts: all
  gather_facts: false

  tasks:
  - name: create nvidia-device-plugin
    shell: "kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.13.0/nvidia-device-plugin.yml"
    become: yes
    become_user: root

  - name: copy testgpu.yml
    copy:
      src: files/testgpu.yml
      dest: /root/testgpu.yml
      owner: root
      group: root
      mode: 0644
    become: yes
    become_user: root

  - name: apply testgpu.yml
    shell: "kubectl apply -f testgpu.yml"
    become: yes
    become_user: root

  - name: wait for K8s cluster to finish GPU testing
    wait_for:
      timeout: 30

  - name: make sure all services and pods are running normally
    shell: "kubectl get pods --all-namespaces -o wide"
    register: kubectl_msg
    become: yes
    become_user: root

  - name: debug - make sure all services and pods are running normally
    debug:
      msg: "{{ kubectl_msg.stdout.split('\n') }}"
    become: yes
    become_user: root

  - name: check logs on gpu-pod test pod
    shell: "kubectl logs gpu-pod"
    register: kubectl_msg
    become: yes
    become_user: root

  - name: debug - check logs on gpu-pod test pod
    debug:
      msg: "{{ kubectl_msg.stdout.split('\n') }}"
    become: yes
    become_user: root
